server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: 'kecal'
    url: jdbc:postgresql://postgres:5432/customer
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl_auto: create-drop
    show-sql: true
  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    enabled: false

logging:
  pattern:
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-}]"

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
