server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: 'kecal'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl_auto: create-drop
    show-sql: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
logging:
  pattern:
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-}]"
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
