server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    username: 'kecal'
    url: jdbc:postgresql://postgres:5432/notification
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl_auto: update
    show-sql: true
  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

logging:
  pattern:
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-}]"

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'

rabbit:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key
