server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: 'kecal'
    url: jdbc:postgresql://localhost:5432/fraud
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl_auto: update
    show-sql: true
logging:
  pattern:
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-}]"
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    enabled: false
